# Generated by Django 5.0.3 on 2024-03-18 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='userOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 14, 32, 38, 655092)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='task',
            field=models.TextField(default='Task description'),
        ),
    ]
