# Generated by Django 5.0.3 on 2024-03-18 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_userorder_alter_todoitem_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
