%% File automatically generated by autoscore.scm

\version "2.19"
\include "incipit-staves.ly"
\include "music.ly"
\include "villancico.ly"

\score {
<<

\new ChoirStaff = "ChI"
<<

\new Staff
<<
\IncipitStaff "Soprano" "S." { \IncipitS }
\new Voice = "S" { \MusicS }
\new Lyrics \lyricsto "S"{ \LyricsS }
>>

\new Staff
<<
\IncipitStaff "Alto" "A." { \IncipitA }
\new Voice = "A" { \MusicA }
\new Lyrics \lyricsto "A"{ \LyricsA }
>>

\new Staff
<<
\IncipitStaff "Tenor" "T." { \IncipitT }
\new Voice = "T" { \MusicT }
\new Lyrics \lyricsto "T"{ \LyricsT }
>>
>>


\new Staff
<<
\IncipitStaff "Basso continuo" "Bc." { \IncipitBc }
\new Voice = "Bc" { \MusicBc }
\new FiguredBass { \FiguresBc }
>>
>>
}
