%% File automatically generated by autoscore.scm

IncipitS = {

}

IncipitA = {

}

IncipitT = {

}

IncipitBc = {

}

MusicS = {

}

MusicA = {

}

MusicT = {

}

MusicBc = {

}

FiguresBc = \figuremode {

}

