%% File automatically generated by autoscore.scm

IncipitS= {

}

IncipitA= {

}

IncipitT= {

}

IncipitBc= {

}

MusicS= {

}

MusicA= {

}

MusicT= {

}

MusicBc= {

}

LyricsS= \lyricmode {

}

LyricsA= \lyricmode {

}

LyricsT= \lyricmode {

}

FiguresBc= \figuremode {

}

