# Generated by Django 5.0.4 on 2024-05-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_fact_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='img',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
