# Generated by Django 5.0.3 on 2024-03-26 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 14, 27, 18, 732523)),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
