# Generated by Django 5.0.3 on 2024-03-26 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todoitem_deadline_todoitem_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 14, 27, 46, 719265, tzinfo=datetime.timezone.utc)),
        ),
    ]
