# Generated by Django 5.0.3 on 2024-03-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todoitem_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='web_id',
            field=models.CharField(default='', max_length=36),
        ),
    ]
