# Generated by Django 5.0.3 on 2024-03-27 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_remove_todoitem_id_alter_todoitem_web_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='is_done',
            new_name='isDone',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='user_order',
            new_name='userOrder',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='web_id',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='deadlineDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.CharField(default='', max_length=80),
        ),
    ]
