# Generated by Django 5.0.3 on 2024-03-27 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_alter_todoitem_deadlinedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='deadlineDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
