%% File automatically generated by autoscore.scm

% INCIPITS

IncipitSolo = {

}

IncipitBc = {

}

% MUSIC

MusicSolo = {

}

MusicBc = {

}

% LYRICS

LyricsSolo = \lyricmode {

}

% FIGURES

FiguresBc = \figuremode {

}

