%% File automatically generated by autoscore.scm

\version "2.19"

\include "villancico.ly"
\include "header.ly"
\include "music.ly"
\include "lyrics.ly"

\score {
<<

\new Staff
<<
\IncipitStaff "SOLO" "" { \IncipitSolo }
\new Voice = "Solo" { \MusicSolo }
\new Lyrics \lyricsto "Solo"{ \LyricsSolo }
>>

\new Staff
<<
\IncipitStaff "BASSO CONTINUO" "" { \IncipitBc }
\new Voice = "Bc" { \MusicBc }
\new FiguredBass { \FiguresBc }
>>
>>
}
